services:
  db:
    image: mysql:8.0
    container_name: mysql-usuario
    restart: always

    environment:
      MYSQL_DATABASE: kernel_panic_db
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3313:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kp-network

  app:
    build:
      context: ./usuario-service
      dockerfile: Dockerfile

    container_name: usuario-service-app

    ports:
      - "8083:8083"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kernel_panic_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - INTERNAL_API_KEY=kp-internal-key

    volumes:
      - ./usuario-service:/app
      - ~/.m2:/root/.m2

    depends_on:
      db:
        condition: service_healthy
    networks:
      kp-network:
        aliases:
          - usuario-service-app

volumes:
  mysql_data:

networks:
  kp-network:
    external: true
